# Generated by Django 3.2.15 on 2022-10-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='end_date',
            field=models.DateField(default="2012-09-04"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshift',
            name='start_date',
            field=models.DateField(default="2012-09-04"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshift',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
